export { AnimateContent } from './animated-content.component'
export { DashboardItem } from './dashboard-item.component'
export { FooterComponent as Footer } from './footer.component'
export { Header } from './header.component'
export { Menu } from './menu.component'
export { ProductList } from './POS/product-list.component'
export { Product } from './POS/product.component'
export { RecentProduct } from './POS/recent-product.component'
export { ToggleMenu } from './POS/toggle-menu.component'
